version: '3.8'
services:
  nnsvs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nnsvs-sample
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    image: nnsvs
    init: true
    network_mode: bridge
    ports:
      - '8888:8888'
    runtime: nvidia
    shm_size: '2gb'
    volumes:
      - .:/workspace
